_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 105
            "2":
                - 1
                - 5
                - 30
                - 41
                - 49
                - 53
                - 55
                - 80
                - 105
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.1
            "8":
                - 2
                - 5
                - 13
            "12": 0.19.1
            "13": linux-x86_64
batch:
    value: 32
dropout:
    value: 0.2282718983963253
lr0:
    value: 0.0004658060218790082
lrf:
    value: 0.025000842643482717
momentum:
    value: 0.31114855497850147
optimizer:
    value: auto
weight_decay:
    value: 0.0019755269299984784
