_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 5
                - 53
                - 105
            "2":
                - 1
                - 5
                - 30
                - 41
                - 49
                - 53
                - 80
                - 105
            "3":
                - 2
                - 14
                - 55
            "4": 3.11.13
            "5": 0.20.1
            "8":
                - 2
                - 13
            "12": 0.20.1
            "13": linux-x86_64
batch:
    value: 8
dropout:
    value: 0.15038848747598235
lr0:
    value: 0.005679734909977713
lrf:
    value: 0.0825224324330394
momentum:
    value: 0.6592768724226196
optimizer:
    value: RAdam
weight_decay:
    value: 0.005443465941073494
