_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 5
                - 53
                - 105
            "2":
                - 1
                - 5
                - 30
                - 41
                - 49
                - 53
                - 80
                - 105
            "3":
                - 2
                - 14
                - 55
            "4": 3.11.13
            "5": 0.20.1
            "8":
                - 2
                - 13
            "12": 0.20.1
            "13": linux-x86_64
batch:
    value: 16
dropout:
    value: 0.1459325582673221
lr0:
    value: 0.008902309489816183
lrf:
    value: 0.006963535198690801
momentum:
    value: 0.4279974486731016
optimizer:
    value: auto
weight_decay:
    value: 0.0018077984042396305
