_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 5
                - 53
                - 105
            "2":
                - 1
                - 5
                - 30
                - 41
                - 49
                - 53
                - 80
                - 105
            "3":
                - 2
                - 14
                - 55
            "4": 3.11.13
            "5": 0.20.1
            "8":
                - 2
                - 13
            "12": 0.20.1
            "13": linux-x86_64
batch:
    value: 16
dropout:
    value: 0.176305565927137
lr0:
    value: 0.002985181561094582
lrf:
    value: 0.007637334548158692
momentum:
    value: 0.44213030496075406
optimizer:
    value: auto
weight_decay:
    value: 0.001290598140683867
