_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 5
                - 53
                - 105
            "2":
                - 1
                - 5
                - 30
                - 41
                - 49
                - 53
                - 80
                - 105
            "3":
                - 2
                - 14
                - 55
            "4": 3.11.13
            "5": 0.20.1
            "8":
                - 2
                - 13
            "12": 0.20.1
            "13": linux-x86_64
batch:
    value: 32
dropout:
    value: 0.017281299425119034
lr0:
    value: 0.008836876763323943
lrf:
    value: 0.02060076185069251
momentum:
    value: 0.45839644193258033
optimizer:
    value: auto
weight_decay:
    value: 0.0050328777770040495
