_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 5
                - 53
                - 105
            "2":
                - 1
                - 5
                - 30
                - 41
                - 49
                - 53
                - 80
                - 105
            "3":
                - 2
                - 14
                - 55
            "4": 3.11.13
            "5": 0.20.1
            "8":
                - 2
                - 13
            "12": 0.20.1
            "13": linux-x86_64
batch:
    value: 16
dropout:
    value: 0.008389170314647653
lr0:
    value: 0.007916985435299098
lrf:
    value: 0.001784965333004008
momentum:
    value: 0.5577029333278861
optimizer:
    value: auto
weight_decay:
    value: 0.004840688749254518
