_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 5
                - 53
                - 105
            "2":
                - 1
                - 5
                - 30
                - 41
                - 49
                - 53
                - 80
                - 105
            "3":
                - 2
                - 14
                - 55
            "4": 3.11.13
            "5": 0.20.1
            "8":
                - 2
                - 13
            "12": 0.20.1
            "13": linux-x86_64
batch:
    value: 32
dropout:
    value: 0.1117224652801894
lr0:
    value: 0.009278515930075112
lrf:
    value: 0.013547306435538614
momentum:
    value: 0.6834383257523504
optimizer:
    value: auto
weight_decay:
    value: 0.00012008330958705408
