_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 5
                - 53
                - 105
            "2":
                - 1
                - 5
                - 30
                - 41
                - 49
                - 53
                - 80
                - 105
            "3":
                - 2
                - 14
                - 55
            "4": 3.11.13
            "5": 0.20.1
            "8":
                - 2
                - 13
            "12": 0.20.1
            "13": linux-x86_64
batch:
    value: 16
dropout:
    value: 0.29530035516515635
lr0:
    value: 0.002564850396284838
lrf:
    value: 0.017990460603471127
momentum:
    value: 0.7440449235354166
optimizer:
    value: auto
weight_decay:
    value: 0.00032391941981014697
