_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 5
                - 53
                - 105
            "2":
                - 1
                - 5
                - 30
                - 41
                - 49
                - 53
                - 80
                - 105
            "3":
                - 2
                - 14
                - 55
            "4": 3.11.13
            "5": 0.20.1
            "8":
                - 2
                - 13
            "12": 0.20.1
            "13": linux-x86_64
batch:
    value: 8
dropout:
    value: 0.193805216608414
lr0:
    value: 0.005739361272134397
lrf:
    value: 0.04866101584655495
momentum:
    value: 0.3872473703566647
optimizer:
    value: AdamW
weight_decay:
    value: 0.009359749735758616
