_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 105
            "2":
                - 1
                - 5
                - 30
                - 41
                - 49
                - 53
                - 55
                - 80
                - 105
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.1
            "8":
                - 2
                - 5
                - 13
            "12": 0.19.1
            "13": linux-x86_64
batch:
    value: 8
dropout:
    value: 0.2995260151547096
lr0:
    value: 0.0005488341632754884
lrf:
    value: 0.04925558177719559
momentum:
    value: 0.28364186026106086
optimizer:
    value: RAdam
weight_decay:
    value: 0.0077563495397472045
