_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 5
                - 53
                - 105
            "2":
                - 1
                - 5
                - 30
                - 41
                - 49
                - 53
                - 80
                - 105
            "3":
                - 2
                - 14
                - 55
            "4": 3.11.13
            "5": 0.20.1
            "8":
                - 2
                - 13
            "12": 0.20.1
            "13": linux-x86_64
batch:
    value: 32
dropout:
    value: 0.007678901536103677
lr0:
    value: 0.007533158846430859
lrf:
    value: 0.011802389046852015
momentum:
    value: 0.726412182411393
optimizer:
    value: auto
weight_decay:
    value: 0.000875560991270704
