_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 5
                - 53
                - 105
            "2":
                - 1
                - 5
                - 30
                - 41
                - 49
                - 53
                - 80
                - 105
            "3":
                - 2
                - 14
                - 55
            "4": 3.11.13
            "5": 0.20.1
            "8":
                - 2
                - 13
            "12": 0.20.1
            "13": linux-x86_64
batch:
    value: 16
dropout:
    value: 0.1571470083325321
lr0:
    value: 0.0062333767366384695
lrf:
    value: 0.02041930813878613
momentum:
    value: 0.9238125948879284
optimizer:
    value: auto
weight_decay:
    value: 0.00036655783842640257
