_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 105
            "2":
                - 1
                - 5
                - 30
                - 41
                - 49
                - 53
                - 55
                - 80
                - 105
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.1
            "8":
                - 2
                - 5
                - 13
            "12": 0.19.1
            "13": linux-x86_64
batch:
    value: 16
dropout:
    value: 0.1740107604547926
lr0:
    value: 0.007344142377132106
lrf:
    value: 0.05069003007875239
momentum:
    value: 0.7171941297070139
optimizer:
    value: RAdam
weight_decay:
    value: 0.001800919233160271
